source 'https://rubygems.org'

gem 'rails', '3.2.16'
gem 'stemmify'
gem 'activerecord-import', '~> 0.3.1'
gem 'sequel'
gem 'triez'

gem 'libv8'

# Use PostgreSQL
gem 'pg', :require => 'pg'

group :development do
end

group :test do
end

group :production do
 gem 'thin'
 
 # Use unicorn as the app server
 gem 'unicorn'
end


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'will_paginate', '>= 3.0.pre'
gem 'devise', '3.0.3'


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# To use debugger
# gem 'debugger'
