services:
  elasticsearch:
    platform: linux/amd64
    build: ./elasticsearch
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cat/health" ]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - discovery.type=single-node

  db:
    platform: linux/amd64
    image: ankane/pgvector
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password

  redis:
    image: redis

  sidekiq:
    platform: linux/amd64
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password

  web:
    platform: linux/amd64
    build: .
    command: rails s -b '0.0.0.0'
    volumes:
      - .:/myapp
    depends_on:
      db:
        condition: service_started
      sidekiq:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
