echo "     ##### Local - valid id/password #####     "
ruby ./test.approx.01.rb "priancho@gmail.com" "password" "http://localhost:3000/dictionaries" "EntrezGene - Homo Sapiens" "Sample dictionary"
echo "     ##### Local - valid guest #####     "
ruby ./test.approx.01.rb "" "" "http://localhost:3000/dictionaries" "EntrezGene - Homo Sapiens" "Sample dictionary"
echo "     ##### Local - invalid email #####     "
ruby ./test.approx.01.rb "priancho@---gmail.com" "password" "http://localhost:3000/dictionaries" "EntrezGene - Homo Sapiens" "Sample dictionary"
echo "     ##### Local - invalid password#####     "
ruby ./test.approx.01.rb "priancho@gmail.com" "pass--word" "http://localhost:3000/dictionaries" "EntrezGene - Homo Sapiens" "Sample dictionary"
echo "     ##### Local - invalid uri #####     "
ruby ./test.approx.01.rb "priancho@gmail.com" "password" "http://localhost:3000/dictionary" "EntrezGene - Homo Sapiens" "Sample dictionary"

