echo "     ##### Local - valid id/password #####     "
ruby ./test.ids_to_labels.01.rb "priancho@gmail.com" "peisia00" "http://pubdictionaries.dbcls.jp/dictionaries" "EntrezGene - Homo Sapiens" "EntrezGene - Mus musculus"
echo "     ##### Local - valid guest #####     "
ruby ./test.ids_to_labels.01.rb "" "" "http://pubdictionaries.dbcls.jp/dictionaries" "EntrezGene - Homo Sapiens" "EntrezGene - Mus musculus"
echo "     ##### Local - invalid dictionaries #####     "
ruby ./test.ids_to_labels.01.rb "" "" "http://pubdictionaries.dbcls.jp/dictionaries" "EntrezGene - Homo Sapiens" "Sample --- dictionary"
echo "     ##### Local - invalid email #####     "
ruby ./test.ids_to_labels.01.rb "priancho@---gmail.com" "peisia00" "http://pubdictionaries.dbcls.jp/dictionaries" "EntrezGene - Homo Sapiens" "EntrezGene - Mus musculus"
echo "     ##### Local - invalid password#####     "
ruby ./test.ids_to_labels.01.rb "priancho@gmail.com" "pass--word" "http://pubdictionaries.dbcls.jp/dictionaries" "EntrezGene - Homo Sapiens" "EntrezGene - Mus musculus"
echo "     ##### Local - invalid uri #####     "
ruby ./test.ids_to_labels.01.rb "priancho@gmail.com" "peisia00" "http://pubdictionaries.dbcls.jp/dictionary" "EntrezGene - Homo Sapiens" "EntrezGene - Mus musculus"

