source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'stemmify'

# Deploy with Capistrano
gem 'capistrano'
gem 'rvm-capistrano'

gem 'libv8'

group :development do
  gem 'sqlite3'
end

group :test do
  gem 'sqlite3'
end

group :production do
 # Use PostgreSQL
 gem 'pg', :require => 'pg'
 gem 'thin'
 
 # Use unicorn as the app server
 gem 'unicorn'
end


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'will_paginate', '>= 3.0.pre'
gem 'devise'


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# To use debugger
# gem 'debugger'
